# Site settings
title:          Hayden Moussa's Blog
description:    "A place to find my weekly progress on Disco Tray projects."
##baseurl:        "/tale"
url:            "https://chesterhow.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Hayden Moussa
  ##url:          https://chester.how
  email:        MoussaHJ@hendrix.edu

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks

remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Excludes
exclude: [ Gemfile, Gemfile.lock]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale